### ISSUE TITLE
for /play-yt the user has to be in a vc

### ISSUE THREAD

**Issue by lukasWastaken** [music-bot-development/music-bot#22]
Es reicht nicht, wenn der Bot in einem vc ist.

Also /join General und danach /play-yt geht nicht, wenn der user nicht in einem vc ist

@Dyzody Soll das so bleiben, oder soll ich das ändern?

**Comment by Dyzody** [comment]
Was meinst du? Der Bot kann nichts abspielen wenn er allein in einem VC ist?
